"""add_resume_chunks

Revision ID: 79d4e8b5cfe2
Revises: 20260825_0003
Create Date: 2026-08-30 16:33:25.199527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79d4e8b5cfe2'
down_revision: Union[str, None] = '20260825_0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


from app.models.profile import SafeVector


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume_chunks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('candidate_profile_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('embedding', SafeVector(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_profile_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_chunks_candidate_profile_id'), 'resume_chunks', ['candidate_profile_id'], unique=False)
    op.create_index(op.f('ix_resume_chunks_id'), 'resume_chunks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resume_chunks_id'), table_name='resume_chunks')
    op.drop_index(op.f('ix_resume_chunks_candidate_profile_id'), table_name='resume_chunks')
    op.drop_table('resume_chunks')
    # ### end Alembic commands ###

